version: "3.8"
name: offshore-stack

configs:
  postgres_config:
    file: "./postgres/postgres.conf"

volumes:
  pg_data:

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    image: "${ELECTRIC_IMAGE:-electricsql/electric:latest}"
    init: true
    environment:
      DATABASE_URL: postgresql://postgres:pg_password@postgres:5432/postgres
      PG_PROXY_PASSWORD: proxy_password
      LOGICAL_PUBLISHER_HOST: electric
      AUTH_MODE: insecure
    ports:
      - 5133:5133
      - 65432:65432
    depends_on:
      - postgres
